# ReadTheDocs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs_sphinx/conf.py

python:
  install:
    - requirements: docs_sphinx/requirements.txt
    - method: pip
      path: .

